spring:

  # ── 데이터베이스 ──────────────────────────────────
  datasource:
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ── JPA ──────────────────────────────────────────
  jpa:
    hibernate:
      ddl-auto: update # Entity 클래스를 보고 테이블을 자동
                       # update 는 "테이블이 없으면 만들고, 있으면 변경사항만 반영
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # ── Redis ─────────────────────────────────────────
  data:
    redis:
      host: localhost
      port: 6379

  # ── 메일 ──────────────────────────────────────────
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_PASSWORD} # 발급받은_16자리_앱비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # ── 카카오 소셜 로그인 ─────────────────────────────
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/api/auth/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# ── JWT ───────────────────────────────────────────────
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 1800000     # 30분 (밀리초)
  refresh-expiration: 604800000  # 7일  (밀리초)

# ── 서버 ──────────────────────────────────────────────
server:
  port: 8080

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html         # Swagger UI 접속 경로
    tags-sorter: alpha             # 태그 알파벳 순 정렬
    operations-sorter: alpha       # API 알파벳 순 정렬
  api-docs:
    path: /v3/api-docs             # API 문서 JSON 경로
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Toss Payments
toss:
  secret-key: ${TOSS_SECRET_KEY}
  confirm-url: https://api.tosspayments.com/v1/payments/confirm